# Generated by Django 5.1.7 on 2025-05-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=10)),
                ('escolaridade', models.CharField(choices=[('ENSINO_FUNDAMENTAL', 'Ensino Fundamental'), ('ENSINO_MEDIO', 'Ensino Médio'), ('SUPERIOR', 'Superior'), ('POS_GRADUACAO', 'Pós-Graduação'), ('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado'), ('OUTRO', 'Outro')], max_length=20)),
                ('experiencia', models.TextField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('area', models.CharField(choices=[('TI', 'Tecnologia da Informação'), ('ENG', 'Engenharia'), ('ADM', 'Administração'), ('MKT', 'Marketing'), ('VEND', 'Vendas'), ('RH', 'Recursos Humanos'), ('FIN', 'Finanças'), ('JUR', 'Jurídico'), ('OUTRO', 'Outro')], max_length=20)),
                ('tipo', models.CharField(choices=[('CLT', 'Consolidação das Leis do Trabalho'), ('PJ', 'Pessoa Jurídica'), ('EST', 'Estágio'), ('TRA', 'Treinamento'), ('OUTRO', 'Outro')], max_length=20)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('localizacao', models.CharField(max_length=100)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
