# Generated by Django 5.1.7 on 2025-05-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregos', '0002_alter_candidato_escolaridade_alter_candidato_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='sobrenome',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
