# Generated by Django 5.1.7 on 2025-05-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregos', '0003_candidato_sobrenome'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='sobrenome',
            field=models.CharField(max_length=100),
        ),
    ]
