# Generated by Django 5.1.7 on 2025-05-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregos', '0004_candidato_data_nascimento_alter_candidato_sobrenome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
