<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-09 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisas', '0002_rename_nome_categoria_nome_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome_categoria',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome_produto',
            new_name='nome',
        ),
    ]
=======
# Generated by Django 5.1.7 on 2025-04-09 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisas', '0002_rename_nome_categoria_nome_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome_categoria',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome_produto',
            new_name='nome',
        ),
    ]
>>>>>>> d4f1ef3 (Aula 16-04)
