# Generated by Django 5.1.7 on 2025-04-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_sobrenome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='andrehenssler@gmail.com', max_length=100, unique=True),
        ),
    ]
